name: Swift

on: [push]

jobs:
  build:

    runs-on: macos-12

    steps:
      - uses: actions/checkout@v3
      - uses: swift-actions/setup-swift@v1
        with:
          swift-version: "5.7.0"
      - name: Get swift version
        run: swift --version
      - name: Run build
        run: swift build
      - name: Run test
        run: swift test
